name: model
on:
  push:
    paths: # Run only when files under neuralprophet/ are modified
      - neuralprophet/**
    branches: # Run only on these branches
      - main
      - develop
  pull_request: # Run on pull requests
    branches:
      - main
      - develop
jobs:
  metrics:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: iterative/setup-dvc@v1
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -e .
          pip3 install pytest
          pip3 install kaleido # required for plotly export
      - name: Train model
        run: |
          pytest tests/test_model_performance.py
      - name: Compare performance
        run: |
          git config --global --add safe.directory /__w/neural_prophet/neural_prophet # Allow CML to access the repo
          git fetch --prune # Fetch all branches
          echo "## Model Benchmark" >> report.md
          # Use CML to create the metrics report https://dvc.org/doc/command-reference/metrics/diff
          dvc metrics diff --targets tests/metrics --recursive --all --precision 4 --md main >> report.md
          echo "## Model Training" >> report.md
          echo "**PeytonManning**" >> report.md
          cml publish  tests/metrics/PeytonManning.png --md >> report.md
          echo "**YosemiteTemps**" >> report.md
          cml publish  tests/metrics/YosemiteTemps.png --md >> report.md
          echo "**AirPassengers**" >> report.md
          cml publish  tests/metrics/AirPassengers.png --md >> report.md
      - name: Publish report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          cml comment update --pr report.md # post to PR
          cml check create --title=ModelReport report.md # update status of check in PR