name: CML
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      # may need to setup Node.js & Python3 on e.g. self-hosted
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '16'
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.x'
      #- uses: iterative/setup-cml@v1
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # - name: Install Python 3
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"
      #     cache: 'pip' # caching pip dependencies
      - uses: iterative/setup-dvc@v1
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -e .
      - name: Train model
        run: |
          python tests/cml/train_benchmark_models.py
      - name: Compare performance
        run: |
          git config --global --add safe.directory /__w/neural_prophet/neural_prophet
          git fetch --prune
          # https://dvc.org/doc/command-reference/metrics/diff
          dvc metrics diff --targets tests/cml/metrics.json --precision 4 --md 74530e5 >> report.md
      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          cml comment create report.md